### ISSUE TITLE
Sponsors page

### ISSUE THREAD

**Issue by aurorasmiles** [PaperMC/website#5]
- Explanation (can be more or less copied from current page https://papermc.io/sponsors)
- Link to OC/GH Sponsors
- Sponsor List
  - Sorted by amount donated?
  - Maybe colored ring around the avatars
  - The current default avatars look ugly

**Comment by Cubxity** [comment]
Implemented in https://github.com/PaperMC/website/commit/ecf4f98a836a77044045abd62c05a75f610b03cd
