### ISSUE TITLE
build explorer table header hides nav software dropdown

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/website#69]
![image](https://github.com/PaperMC/website/assets/2185527/de3316b6-591a-4705-8797-dafdd8b30561)

I tried raising the z index of the dropdown from 50 (which is the same as the table header) to 100, but that didnt change it?

**Comment by yannicklamprecht** [comment]
1. Delete: `.w-full .relative` from `html.lpyjjhm.idc0_348 body div#__next main.flex-1 div.flex.flex-col.h-screen div.flex-1.flex.flex-row.min-h-0 div.flex-1.overflow-auto table.w-full.relative` so basically the table.
2. Delete `z-50` from `html.lpyjjhm.idc0_348 body div#__next main.flex-1 div.flex.flex-col.h-screen div.flex-1.flex.flex-row.min-h-0 div.flex-1.overflow-auto table.w-full.relative thead.sticky.top-0.z-50.bg-background-light-10.dark:bg-background-dark-90.shadow-sm`

Fixed it for me.
