### ISSUE TITLE
Site having incredibly slow download speeds

### ISSUE THREAD

**Issue by Pixeluted** [PaperMC/website#92]
When downloading any jar from the official site the downloads speeds are low as 60kb/s which is not normal.

I have checked whether this is my issue but my internet is running normally and downloading from other sites is downloading at fast speeds.

However this doesn't seem like worldwide issue since servers can download the jar with normal speeds but as I have checked if it could be my issue but I didn't find any, so I have no idea.

**Comment by MiniDigger** [comment]
There is nothing we can do, all downloads are handled by cloudflare, so you have connections issues to cloudflare. Check with your ISP or something

**Comment by Pixeluted** [comment]
I don't really think this is problem with ISP
![image](https://github.com/PaperMC/website/assets/78791776/b2680c44-9378-4c44-8106-651f871aae51)

**Comment by Pixeluted** [comment]
Seems to be problem with my browser now clue why but on other one it's downloading normally.
